### ISSUE TITLE
ModuleNotFoundError: No module named 'frcnn.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by Mayllisa** [phil-bergmann/tracking_wo_bnw#1]
when I run the Tracktor by executing:
`python experiments/scripts/test_tracktor.py`
I got an error as follows:

> Traceback (most recent call last):
>   File "experiments/scripts/test_tracktor.py", line 16, in <module>
>     from tracktor.datasets.factory import Datasets
>   File "tracktor2/tracking_wo_bnw/src/tracktor/datasets/factory.py", line 2, in <module>
>     from .mot_wrapper import MOT17_Wrapper, MOT19CVPR_Wrapper, MOT17LOWFPS_Wrapper
>   File "/home/ymy/tracktor2/tracking_wo_bnw/src/tracktor/datasets/mot_wrapper.py", line 4, in <module>
>     from .mot_sequence import MOT17_Sequence, MOT19CVPR_Sequence, MOT17LOWFPS_Sequence
>   File "tracktor2/tracking_wo_bnw/src/tracktor/datasets/mot_sequence.py", line 12, in <module>
>     from frcnn.model import test
>   File "tracktor2/tracking_wo_bnw/src/frcnn/frcnn/model/test.py", line 22, in <module>
>     from .nms_wrapper import nms
>   File "tracktor2/tracking_wo_bnw/src/frcnn/frcnn/model/nms_wrapper.py", line 11, in <module>
>     from ..nms.pth_nms import pth_nms
>   File tracktor2/tracking_wo_bnw/src/frcnn/frcnn/nms/pth_nms.py", line 2, in <module>
>     from ._ext import nms
>   File "tracktor2/tracking_wo_bnw/src/frcnn/frcnn/nms/_ext/nms/__init__.py", line 3, in <module>
>     from ._nms import lib as _lib, ffi as _ffi
> ModuleNotFoundError: No module named 'frcnn.nms._ext.nms._nms'
> 

The _nms.py file does not exsit under the path "tracktor2/tracking_wo_bnw/src/frcnn/frcnn/nms/_ext/nms/_nms.py"

**Comment by timmeinhardt** [comment]
Did you successfully complete step 3 of our installation instructions?

**Comment by timmeinhardt** [comment]
If the error got resolved please close this issue. Thank you!

**Comment by nathanlem1** [comment]
I am facing the same problem. I have successfully installed the step 3 installation but this problem is still there.

**Comment by timmeinhardt** [comment]
Did you check whether the compilations of step 3 finished successfully? A missing `_nms.py` file indicated that something went wrong in step 3.

**Comment by nathanlem1** [comment]
It shows this error:

  File "experiments/scripts/test_tracktor.py", line 16, in <module>
    from tracktor.datasets.factory import Datasets
  File "/storage/AnyVision/tracking_wo_bnw/src/tracktor/datasets/factory.py", line 2, in <module>
    from .mot_wrapper import MOT17_Wrapper, MOT19CVPR_Wrapper, MOT17LOWFPS_Wrapper
  File "/storage/AnyVision/tracking_wo_bnw/src/tracktor/datasets/mot_wrapper.py", line 4, in <module>
    from .mot_sequence import MOT17_Sequence, MOT19CVPR_Sequence, MOT17LOWFPS_Sequence
  File "/storage/AnyVision/tracking_wo_bnw/src/tracktor/datasets/mot_sequence.py", line 12, in <module>
    from frcnn.model import test
  File "/storage/AnyVision/tracking_wo_bnw/src/frcnn/frcnn/model/test.py", line 22, in <module>
    from .nms_wrapper import nms
  File "/storage/AnyVision/tracking_wo_bnw/src/frcnn/frcnn/model/nms_wrapper.py", line 11, in <module>
    from ..nms.pth_nms import pth_nms
  File "/storage/AnyVision/tracking_wo_bnw/src/frcnn/frcnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/storage/AnyVision/tracking_wo_bnw/src/frcnn/frcnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /storage/AnyVision/tracking_wo_bnw/src/frcnn/frcnn/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

**Comment by timmeinhardt** [comment]
Please check the compilation in step 3 and whether is finished successfully. These errors are most likely due to a failed compilation. And one can easily miss that the compilation failed.

**Comment by nathanlem1** [comment]
There is no error during installation of step except some warnings. I tried using both cuda-9.0 and cuda-10.0.

**Comment by nathanlem1** [comment]
Yes, I used PyTorch 0.3.1 after making sure it doesn't work with the latest PyTorch version.

**Comment by timmeinhardt** [comment]
The error message does not say that it can not find `lib` and `ffi`. It just says that an error occured while importing the two from `._nms`. The error comes when the `_nms.so` library file encounters a symbol that it does not know. And that symbol is `__cudaPopCallConfiguration `. And apparently this is an issue of a mismatch between PyTorch und CUDA version.
