### ISSUE TITLE
ModuleNotFoundError: No module named 'mask_rcnn_tracktor'

### ISSUE THREAD

**Issue by HongliXiao** [phil-bergmann/tracking_wo_bnw#177]
A ModuleNotFoundError occurred when I am trying to run "\experiments\scripts\obj_det_training.py", can  you help me find the reason? I cannot find the mask_rcnn_tracktor and keypoint_rcnn_tracktor in your provided files.

PS G:\Research\tracking_wo_bnw-master> & "D:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe" g:/Research/tracking_wo_bnw-master/experiments/scripts/obj_det_training.py
Traceback (most recent call last):
  File "g:/Research/tracking_wo_bnw-master/experiments/scripts/obj_det_training.py", line 18, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
PS G:\Research\tracking_wo_bnw-master> & D:/Anaconda3/envs/tracktor/python.exe g:/Research/tracking_wo_bnw-master/experiments/scripts/obj_det_training.py
Traceback (most recent call last):
  File "g:/Research/tracking_wo_bnw-master/experiments/scripts/obj_det_training.py", line 32, in <module>
    import models
  File "G:\Research\tracking_wo_bnw-master\src\obj_det\models.py", line 23, in <module>
    from mask_rcnn_tracktor import MaskRCNNTracktor
ModuleNotFoundError: No module named 'mask_rcnn_tracktor'

**Comment by HongliXiao** [comment]
![image](https://user-images.githubusercontent.com/65099349/210524115-010dcf32-7547-4f3a-a923-3568fe0dcd0f.png)

**Comment by timmeinhardt** [comment]
I just pushed some changes with the missing files. Sorry for the delay!
